# Generated by Django 4.2.7 on 2025-09-22 06:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع المحادثة')),
                ('total_messages', models.PositiveIntegerField(default=0, verbose_name='إجمالي الرسائل')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر رسالة')),
                ('is_closed', models.BooleanField(default=False, verbose_name='مغلقة')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('citizen_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='تقييم المواطن')),
                ('citizen_feedback', models.TextField(blank=True, verbose_name='تعليق المواطن')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_conversations', to=settings.AUTH_USER_MODEL, verbose_name='المواطن')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_conversations', to=settings.AUTH_USER_MODEL, verbose_name='أغلقها')),
                ('last_message_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_messages', to=settings.AUTH_USER_MODEL, verbose_name='آخر مرسل')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representative_conversations', to=settings.AUTH_USER_MODEL, verbose_name='النائب')),
            ],
            options={
                'verbose_name': 'محادثة',
                'verbose_name_plural': 'المحادثات',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('content', models.TextField(help_text='الحد الأقصى 500 حرف', validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='محتوى الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة')),
                ('is_system_message', models.BooleanField(default=False, verbose_name='رسالة نظام')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='naebak_messages.conversation', verbose_name='المحادثة')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='naebak_messages.message', verbose_name='رد على')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('user_type', models.CharField(choices=[('citizen', 'مواطن'), ('representative', 'نائب'), ('admin', 'مدير')], max_length=20, verbose_name='نوع المستخدم')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='رقم الهاتف')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='الصورة الشخصية')),
                ('representative_id', models.UUIDField(blank=True, null=True, verbose_name='معرف النائب في خدمة المحتوى')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='الدائرة الانتخابية')),
                ('governorate', models.CharField(blank=True, max_length=50, verbose_name='المحافظة')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='إشعارات البريد الإلكتروني')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='إشعارات الرسائل النصية')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
                'indexes': [models.Index(fields=['user_type'], name='naebak_mess_user_ty_dec1ab_idx'), models.Index(fields=['representative_id'], name='naebak_mess_represe_3f9ad1_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notification_type', models.CharField(choices=[('new_message', 'رسالة جديدة'), ('conversation_closed', 'إغلاق محادثة'), ('system_update', 'تحديث النظام'), ('maintenance', 'صيانة')], max_length=20, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الإشعار')),
                ('message', models.TextField(verbose_name='محتوى الإشعار')),
                ('related_object_id', models.UUIDField(blank=True, null=True, verbose_name='معرف الكائن المرتبط')),
                ('action_url', models.URLField(blank=True, verbose_name='رابط الإجراء')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار النظام',
                'verbose_name_plural': 'إشعارات النظام',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='naebak_mess_user_id_417d20_idx'), models.Index(fields=['notification_type'], name='naebak_mess_notific_c48a53_idx'), models.Index(fields=['created_at'], name='naebak_mess_created_15cb8f_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('messages_sent', models.PositiveIntegerField(default=0, verbose_name='الرسائل المرسلة')),
                ('messages_received', models.PositiveIntegerField(default=0, verbose_name='الرسائل المستلمة')),
                ('conversations_started', models.PositiveIntegerField(default=0, verbose_name='المحادثات المبدوءة')),
                ('conversations_closed', models.PositiveIntegerField(default=0, verbose_name='المحادثات المغلقة')),
                ('avg_response_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='متوسط وقت الرد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إحصائيات الرسائل',
                'verbose_name_plural': 'إحصائيات الرسائل',
                'indexes': [models.Index(fields=['user', 'date'], name='naebak_mess_user_id_81d343_idx'), models.Index(fields=['date'], name='naebak_mess_date_bed218_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MessageReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('reason', models.CharField(choices=[('spam', 'رسائل مزعجة'), ('inappropriate', 'محتوى غير مناسب'), ('harassment', 'تحرش أو إساءة'), ('fake', 'معلومات مضللة'), ('other', 'أخرى')], max_length=20, verbose_name='سبب الإبلاغ')),
                ('description', models.TextField(blank=True, verbose_name='وصف الإبلاغ')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='تمت المراجعة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('action_taken', models.TextField(blank=True, verbose_name='الإجراء المتخذ')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='naebak_messages.message', verbose_name='الرسالة')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reports', to=settings.AUTH_USER_MODEL, verbose_name='المبلغ')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='راجعها')),
            ],
            options={
                'verbose_name': 'إبلاغ عن رسالة',
                'verbose_name_plural': 'الإبلاغات عن الرسائل',
                'indexes': [models.Index(fields=['is_reviewed', 'created_at'], name='naebak_mess_is_revi_b2e508_idx'), models.Index(fields=['reason'], name='naebak_mess_reason_8978be_idx')],
                'unique_together': {('message', 'reporter')},
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='naebak_mess_convers_a078f4_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'is_read'], name='naebak_mess_sender__1dbfc1_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_system_message'], name='naebak_mess_is_syst_23dec1_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['citizen', 'representative'], name='naebak_mess_citizen_806b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_closed', 'last_message_at'], name='naebak_mess_is_clos_9da79b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_at'], name='naebak_mess_created_c5b301_idx'),
        ),
    ]
