# Generated by Django 4.2.7 on 2025-09-22 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naebak_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون بين 10 و 15 رقم', regex='^\\d{10,15}$')], verbose_name='رقم الهاتف'),
        ),
    ]
